name: build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'

    - name: Build
      run: npm build
      working-directory: ./Frontend